### ISSUE TITLE
RecursionError on wayland (sway)

### ISSUE THREAD

**Issue by akvadrako** [pygfx/wgpu-py#109]
With a fresh clone and virtualenv I followed the instructions for running from a checkout and then tried to run the triangle example. I got this error:

```
$ ./venv/bin/python examples/triangle_glfw.py 2>&1
Traceback (most recent call last):
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 52, in _reraise
    raise exception.with_traceback(traceback)
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 595, in callback_wrapper
    return func(*args, **kwargs)
  File "/home/dev/repos/wgpu-py/wgpu/gui/glfw.py", line 95, in _on_pixelratio_change
    self._set_logical_size()
  File "/home/dev/repos/wgpu-py/wgpu/gui/glfw.py", line 136, in _set_logical_size
    glfw.set_window_size(
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 1272, in set_window_size
    _glfw.glfwSetWindowSize(window, width, height)
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 616, in errcheck
    _reraise(exc[1], exc[2])
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 52, in _reraise
    raise exception.with_traceback(traceback)
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 595, in callback_wrapper
    return func(*args, **kwargs)
  File "/home/dev/repos/wgpu-py/wgpu/gui/glfw.py", line 95, in _on_pixelratio_change
    self._set_logical_size()
  File "/home/dev/repos/wgpu-py/wgpu/gui/glfw.py", line 136, in _set_logical_size
    glfw.set_window_size(
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 1272, in set_window_size
    _glfw.glfwSetWindowSize(window, width, height)
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 616, in errcheck
    _reraise(exc[1], exc[2])
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 52, in _reraise
    raise exception.with_traceback(traceback)
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 595, in callback_wrapper
    return func(*args, **kwargs)
  File "/home/dev/repos/wgpu-py/wgpu/gui/glfw.py", line 95, in _on_pixelratio_change
    self._set_logical_size()
  File "/home/dev/repos/wgpu-py/wgpu/gui/glfw.py", line 136, in _set_logical_size
    glfw.set_window_size(
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 1272, in set_window_size
    _glfw.glfwSetWindowSize(window, width, height)
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 616, in errcheck
    _reraise(exc[1], exc[2])
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 52, in _reraise
    raise exception.with_traceback(traceback)
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 595, in callback_wrapper
...
    raise exception.with_traceback(traceback)
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 595, in callback_wrapper
    return func(*args, **kwargs)
  File "/home/dev/repos/wgpu-py/wgpu/gui/glfw.py", line 95, in _on_pixelratio_change
    self._set_logical_size()
  File "/home/dev/repos/wgpu-py/wgpu/gui/glfw.py", line 136, in _set_logical_size
    glfw.set_window_size(
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 1272, in set_window_size
    _glfw.glfwSetWindowSize(window, width, height)
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 616, in errcheck
    _reraise(exc[1], exc[2])
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 52, in _reraise
    raise exception.with_traceback(traceback)
  File "/home/dev/repos/wgpu-py/venv/lib/python3.8/site-packages/glfw/__init__.py", line 595, in callback_wrapper
    return func(*args, **kwargs)
  File "/home/dev/repos/wgpu-py/wgpu/gui/glfw.py", line 99, in _on_size_change
    self._logical_size = self._get_logical_size()
  File "/home/dev/repos/wgpu-py/wgpu/gui/glfw.py", line 116, in _get_logical_size
    psize = glfw.get_framebuffer_size(self._window)
RecursionError: maximum recursion depth exceeded
```

- Ubuntu 20.04
- sway 1.4-dffc184a

**Comment by almarklein** [comment]
Thanks for reporting. We should look into this once we've updated to the latest wgpu-native. Support for Wayland was not great last time I tried in 18.04. Is it any better in 20.04?

**Comment by akvadrako** [comment]
I have been using wayland for about a year and my only complaint is X11-only apps don't have proper high DPI support. Though I use upstream sway; mutter might be better in this regard.

**Comment by almarklein** [comment]
I just played around with Wayland (on Ubuntu 20.04) and could reproduce the error, and fix it. See #122. Things are far from perfect yet, but it should get you further now.

@akvadrako if you have any further tips for running this with Wayland that we could include in the docs, that would be great :)
