### ISSUE TITLE
wgpu-py doesn't ship binaries on RHEL7

### ISSUE THREAD

**Issue by xloem** [pygfx/wgpu-py#313]
This would be easy to resolve if there were clear instructions for installing the library dependency.

```
$ cat /etc/*release
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.9 (Maipo)"
```
```
$ python3 --version
Python 3.10.4+
$ pip3 --version
pip 22.3.1 from /home/user/.local/lib/python3.10/site-packages/pip (python 3.10)
```
```
$ pip3 install wgpu; python3 -c 'import wgpu, wgpu.backends.rs'
Defaulting to user installation because normal site-packages is not writeable
Collecting wgpu
  Downloading wgpu-0.8.2.tar.gz (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 4.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi>=1.15.0rc2 in /home/user/.local/lib/python3.10/site-packages (from wgpu) (1.15.0)
Requirement already satisfied: pycparser in /home/user/.local/lib/python3.10/site-packages (from cffi>=1.15.0rc2->wgpu) (2.21)
Building wheels for collected packages: wgpu
  Building wheel for wgpu (pyproject.toml) ... done
  Created wheel for wgpu: filename=wgpu-0.8.2-py3-none-linux_x86_64.whl size=102839 sha256=b57c5b31a983e66dda0208c78593b268faab165cc0f8b170d52e811633d3a18b
  Stored in directory: /home/user/.cache/pip/wheels/47/fc/42/d6cdb67d25ce726c291a7dc4f514c2b305d330c5637d30a6d2
Successfully built wgpu
Installing collected packages: wgpu
Successfully installed wgpu-0.8.2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/wgpu/backends/rs.py", line 44, in <module>
    from .rs_ffi import ffi, lib, check_expected_version
  File "/home/user/.local/lib/python3.10/site-packages/wgpu/backends/rs_ffi.py", line 85, in <module>
    lib = ffi.dlopen(get_wgpu_lib_path())
  File "/home/user/.local/lib/python3.10/site-packages/wgpu/backends/rs_ffi.py", line 74, in get_wgpu_lib_path
    raise RuntimeError(f"Could not find WGPU library in {embedded_path}")
RuntimeError: Could not find WGPU library in /home/user/.local/lib/python3.10/site-packages/wgpu/resources/libwgpu-release.so
```

**Comment by Korijn** [comment]
See bullet #4 under "Developers" in README.md.

**Comment by almarklein** [comment]
I think it should still be possible to build wgpu-native yourself and then telling wgpu-py where the DLL is via `WGPU_LIB_PATH`, right?

**Comment by xloem** [comment]
I've been pursuing that a little. I ran into issues so started trying the examples. It turns out wgpu-native does not run on my platform itself, unfortunately ( https://github.com/gfx-rs/wgpu-native/issues/230 ).

Thank you for your detailed attention here.

It makes sense there are not clear installation instructions for manually installing wgpu-native when I try the project out: it does not have an installation build phase yet.
