### ISSUE TITLE
Raspberry PI 4B setup log

### ISSUE THREAD

**Issue by dskkato** [pygfx/wgpu-py#438]
This is not issues, but setup log for Raspberry Pi 4B

device

```sh
dskkato@raspberrypi:~ $ cat /sys/firmware/devicetree/base/model 
Raspberry Pi 4 Model B Rev 1.5
```

OS: Raspberry Pi OS (64 bit)
```sh
 dskkato@raspberrypi:~ $ cat /proc/version 
Linux version 6.1.0-rpi4-rpi-v8 (debian-kernel@lists.debian.org)
(gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40)
#1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05)
```

```sh
dskkato@raspberrypi:~ $ python --version
Python 3.11.2
```

---------------------

```sh
git clone https://github.com/pygfx/wgpu-py.git
cd wgpu-py
python -m venv .venv
source .venv/bin/activate
pip install -e .
```

```sh
(.venv) dskkato@raspberrypi:~/workspace/wgpu-py $ python examples/cube.py 
Traceback (most recent call last):
  File "/home/dskkato/workspace/wgpu-py/examples/cube.py", line 8, in <module>
    from wgpu.gui.auto import WgpuCanvas, run
  File "/home/dskkato/workspace/wgpu-py/wgpu/gui/auto.py", line 103, in <module>
    module = _auto_load_backend()
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/dskkato/workspace/wgpu-py/wgpu/gui/auto.py", line 92, in _auto_load_backend
    raise ImportError(msg) from None
ImportError: 

  Could not find either glfw or Qt framework.
  Install glfw using e.g. ``pip install -U glfw``,
  or install a qt framework using e.g. ``pip install -U pyside6``.
  You may also need to run the equivalent of ``apt install libglfw3``.
```

```sh
pip install numpy glfw
```

```sh
(.venv) dskkato@raspberrypi:~/workspace/wgpu-py $ python examples/cube.py 
	EGL context: -robust access
Max vertex shader SSBO == 0 and SSTO != 0. Interpreting as false zero.
Re-initializing Gles context due to Wayland window
	EGL context: -robust access
thread '<unnamed>' panicked at /root/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/2e7fd75/wgpu-hal/src/gles/egl.rs:305:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 556743984
Aborted
```

```sh
sudo apt install mesa-vulkan-drivers 
```
```sh
(.venv) dskkato@raspberrypi:~/workspace/wgpu-py $ python examples/cube.py 
	EGL context: -robust access
Max vertex shader SSBO == 0 and SSTO != 0. Interpreting as false zero.
Missing downlevel flags: DownlevelFlags(FULL_DRAW_INDEX_UINT32)
The underlying API or device in use does not support enough features to be a fully compliant implementation of WebGPU. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to limit the features you use to the supported subset, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.
Re-initializing Gles context due to Wayland window
	EGL context: -robust access
```

**Comment by almarklein** [comment]
Thanks for the detailed setup log!

I see that it falls back to GL. Not sure if e.g. pygfx works on that backend. A quick Google search suggests that it is possible to install Vulkan on Raspberry Pi. Have you tried that?

**Comment by dskkato** [comment]
For Wayland, it may be knowe issues. See https://github.com/pygfx/wgpu-py/issues/92 for example.

**Comment by dskkato** [comment]
I believe all that's left is (as mentioned elsewhare) to wait for the release on CI, so I will close this issue. There is still the pending task of building for armv7, it seems like it would be quite labor-intensive, involving preparations for armv7 container image (manylinux or Raspberry Pi base).

**Comment by almarklein** [comment]
Thanks for this!

It looks like the hardware of the Pi is just not good enough to meet the requirements to be wgpu standard compliant. What it does then is move to "downlevel", which is a set of easier requirements. Most test failures seem to be related to unsupported texture formats (or no filtering supported for certain textures).

I'm curious to see how well pygfx still runs on it, but we can try that another day.

> There is still the pending task of building for armv7, 

I think what we have now is probably enough for now.

**Comment by dskkato** [comment]
Here is test logs running on Raspberry Pi 4B. I have no knowledge of the pygfx test cases and have not checked the logs.

## Test logs

- [pygfx-raspberry-pi-4b-opengl.log](https://github.com/pygfx/wgpu-py/files/13594196/pygfx-raspberry-pi-4b-opengl.log)
- [pygfx-raspberry-pi-4b-vulkan.log](https://github.com/pygfx/wgpu-py/files/13594197/pygfx-raspberry-pi-4b-vulkan.log)

----
## Short summaries

Vulkan backend
```
=========================== short test summary info ============================
FAILED examples/tests/test_examples.py::test_examples_run[offscreen] - TypeEr...
FAILED tests/renderers/test_reactivity.py::test_reactivity_mesh3 - wgpu._clas...
====== 2 failed, 278 passed, 21 skipped, 3 warnings in 743.31s (0:12:23) =======
```

OpenGL backend
```
=========================== short test summary info ============================
FAILED examples/tests/test_examples.py::test_examples_run[offscreen] - TypeEr...
FAILED tests/renderers/test_reactivity.py::test_reactivity_mesh1 - wgpu._clas...
FAILED tests/renderers/test_reactivity.py::test_reactivity_mesh2 - wgpu._clas...
FAILED tests/renderers/test_reactivity.py::test_reactivity_mesh3 - wgpu._clas...
FAILED tests/renderers/test_reactivity.py::test_change_blend_mode - wgpu._cla...
FAILED tests/renderers/test_reactivity.py::test_two_renders_with_same_blend_modes
FAILED tests/renderers/test_reactivity.py::test_two_renders_with_different_blend_modes
====== 7 failed, 273 passed, 21 skipped, 3 warnings in 715.57s (0:11:55) =======
```
