### ISSUE TITLE
Examples don't run - various errors

### ISSUE THREAD

**Issue by StanislavNikolov** [pygfx/wgpu-py#564]
### Describe the bug
Running the examples produces a couple of different errors during [device.create_render_pipeline](https://github.com/pygfx/wgpu-py/blob/62a1a02d96e6275f90b11c65e35aac1e3023f26b/examples/triangle.py#L87)

```
Traceback (most recent call last):
  File "/Users/stjo/wgpu-py/examples/triangle_auto.py", line 18, in <module>
    device = main(canvas)
             ^^^^^^^^^^^^
  File "/Users/stjo/wgpu-py/examples/triangle.py", line 67, in main
    return _main(canvas, device)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stjo/wgpu-py/examples/triangle.py", line 136, in _main
    draw_frame = setup_draw(canvas.get_context(), device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stjo/wgpu-py/examples/triangle.py", line 87, in setup_draw
    render_pipeline = device.create_render_pipeline(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stjo/.venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_api.py", line 1427, in create_render_pipeline
    for buffer_des in vertex["buffers"]:
                      ~~~~~~^^^^^^^^^^^
KeyError: 'buffers'
```

Adding an empty list under the "buffers" key changes the errors

```
Traceback (most recent call last):
  File "/Users/stjo/.venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_api.py", line 133, in _tuple_from_tuple_or_dict
    return tuple(ob[key] for key in fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stjo/.venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_api.py", line 133, in <genexpr>
    return tuple(ob[key] for key in fields)
                 ~~^^^^^
KeyError: 'src_factor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stjo/myx/stjo-matterport-clone/webgpu.py", line 50, in <module>
    render_pipeline = device.create_render_pipeline(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stjo/.venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_api.py", line 1529, in create_render_pipeline
    alpha_blend = _tuple_from_tuple_or_dict(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stjo/.venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_api.py", line 135, in _tuple_from_tuple_or_dict
    raise ValueError(error_msg.format(", ".join(fields)))
ValueError: Expected tuple/key/dict with fields: src_factor, dst_factor, operation
```

### To Reproduce
```sh
pip install wgpu glfw
git clone https://github.com/pygfx/wgpu-py.git
cd wgpu-py/examples
python3 triangles.py
```
Running triangles_auto or triangles_glfw does not change the errors.

### Your environment
```
>>> wgpu.diagnostics.print_report()

██ system:

             platform:  macOS-15.0-arm64-arm-64bit
python_implementation:  CPython
               python:  3.12.5

██ versions:

wgpu:  0.16.0

██ wgpu_native_info:

No data

██ object_counts:

                      count  resource_mem

            Adapter:      0
          BindGroup:      0
    BindGroupLayout:      0
             Buffer:      0
      CanvasContext:      0
      CommandBuffer:      0
     CommandEncoder:      0
 ComputePassEncoder:      0
    ComputePipeline:      0
             Device:      0
     PipelineLayout:      0
           QuerySet:      0
              Queue:      0
       RenderBundle:      0
RenderBundleEncoder:      0
  RenderPassEncoder:      0
     RenderPipeline:      0
            Sampler:      0
       ShaderModule:      0
            Texture:      0
        TextureView:      0

              total:      0             0
```

**Comment by Korijn** [comment]
See https://github.com/pygfx/wgpu-py/issues/537#issuecomment-2202270028
