### ISSUE TITLE
Error in wgpu-py exmaples : no attribute 'request_adapter_sync'

### ISSUE THREAD

**Issue by XiaochaoYan** [pygfx/wgpu-py#616]
### Describe the bug
The examples in https://github.com/pygfx/wgpu-py/tree/main/examples are not working as intended.

### To Reproduce
Running  [cube.py](https://github.com/pygfx/wgpu-py/blob/main/examples/cube.py)
or
[triangle.py](https://github.com/pygfx/wgpu-py/blob/main/examples/triangle.py)

### Observed behavior
Error with the following error message.

Traceback (most recent call last):
  File "C:\Users\XXXX\Desktop\example.py", line 170, in <module>
    draw_frame = setup_drawing_sync(canvas)
  File "C:\Users\XXXX\Desktop\example.py", line 33, in setup_drawing_sync
    adapter = wgpu.gpu.request_adapter_sync(power_preference=power_preference)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GPU' object has no attribute 'request_adapter_sync'. Did you mean: 'request_adapter_async'?

### Screenshots
N/A

### Your environment
Win11 system
Python 3.13.0
cffi        1.17.1
freetype-py 2.5.1
glfw        2.7.0
Jinja2      3.1.4
MarkupSafe  3.0.1
numpy       2.1.2
pip         24.2
pycparser   2.22
pygfx       0.5.0
pylinalg    0.4.1
uharfbuzz   0.41.0
wgpu        0.18.1

**Comment by kushalkolar** [comment]
Looks like you've installed the release version, the examples in the repo correspond to the main branch. You can instead refer to the [examples for the last release](https://github.com/pygfx/wgpu-py/tree/v0.18.1/examples) or [install from main](https://github.com/pygfx/wgpu-py?tab=readme-ov-file#developers)

**Comment by Korijn** [comment]
I'm thinking we should create a pinned issue with title "error when running an example" and provide a standard resolution
